elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  realm: test
  host: http://test:8443

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 800
